name: Volanthius
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: Volanthius - ON THE GRID
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.01914894
  lightness: 0.887234
  saturation: 0.125
  rhythmicContrast: 0.4425532
purpose: []
