layout_spectrum: 0.9893617
color:
  saturation: 0.5297872
  lightness: 0.887234
  brandStrength: 0.01914894
  rhythmicContrast: 0.4425532
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
typography_spectrum: 0.6151018
name: Volanthius
